### PR TITLE
Fix phylo input

### PR DESCRIPTION
**Pull request by joverlee521**
## Description of proposed changes

I missed this in review of https://github.com/nextstrain/dengue/pull/38.
The phylogenetic workflow was still pulling from old S3 URLs
and not the ingest workflow output data.

## Checklist

- [x] Checks pass

### CODE REVIEW

**Comment by joverlee521** [comment]
Triggered [trial phylogenetic workflow run](https://github.com/nextstrain/dengue/actions/runs/8654621898) with 

```
gh workflow run phylogenetic.yaml --ref fix-phylo-input -f trial_name=fix-phylo-input
```

**Comment by j23414** [comment]
Thank you for working on this! I'll be curious how you solve the problem of adding an "Accession URL". The accession is important for investigating outliers in the tree or getting to the full GenBank entry.

Screenshot 2024-04-12 at 9 16 27 AM

I'd been using a post-processing script in zika: https://github.com/nextstrain/zika/blob/9892009b95ea802f288142734614e29f00212922/phylogenetic/scripts/set_final_strain_name.py#L6-L15

But I think you mentioned there may be a more straightforward method: https://github.com/nextstrain/zika/issues/32

**Comment by joverlee521** [comment]
> Thank you for working on this! I'll be curious how you solve the problem of adding an "Accession URL". The accession is important for investigating outliers in the tree or getting to the full GenBank entry.
>
> I'd been using a post-processing script in zika: https://github.com/nextstrain/zika/blob/9892009b95ea802f288142734614e29f00212922/phylogenetic/scripts/set_final_strain_name.py#L6-L15
> 
> But I think you mentioned there may be a more straightforward method: [nextstrain/zika#32](https://github.com/nextstrain/zika/issues/32)

Thanks for bringing this up @j23414, I totally forgot about this issue. 
I've fixed it with 8acbbcaee3397b0cea82447b7ad44e68008f3c2f. Let me know if you have any questions!

**Comment by joverlee521** [comment]
Hmm, [CI failing](https://github.com/nextstrain/dengue/actions/runs/8665946144/job/23765711960?pr=40) is a separate issue due to installation of the [Conda runtime failing](https://github.com/nextstrain/conda-base/actions/runs/8665943916).

**Comment by joverlee521** [comment]
Trial builds have completed and deployed to staging:

https://nextstrain.org/staging/dengue/trial/fix-phylo-input/dengue/all/genome
https://nextstrain.org/staging/dengue/trial/fix-phylo-input/dengue/denv1/genome
https://nextstrain.org/staging/dengue/trial/fix-phylo-input/dengue/denv2/genome
https://nextstrain.org/staging/dengue/trial/fix-phylo-input/dengue/denv3/genome
https://nextstrain.org/staging/dengue/trial/fix-phylo-input/dengue/denv4/genome

**Comment by joverlee521** [comment]
I'll wait to merge this on Monday so I can monitor for anything unexpected. 

I'll probably drop https://github.com/nextstrain/dengue/pull/40/commits/5c850676330dbc2a3c760351ebcd3e989a98a5f7 before merging since I'm working on a better way to split out ingest/phylogenetic GH Action workflows in https://github.com/nextstrain/zika/tree/reusable-workflows

**Comment by joverlee521** [comment]
Manually deleted cache and triggered a new run of [ingest-to-phylogenetic](https://github.com/nextstrain/dengue/actions/runs/8693815603) so that the live builds are actually using the ingested data.

**Pull request merged**
